version: '3.8'

services:
  market:
    container_name: market_c
    build:
      context: .
      dockerfile: market/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      redis-server:
        condition: service_started
    networks:
      - app-network

  pay:
    container_name: pay_c
    build:
      context: .
      dockerfile: pay-service/Dockerfile
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app-network

  redis-server:
    container_name: redis_c
    hostname: redis-server
    #    image: redis:7.4.2-bookworm
    image: redis/redis-stack:7.2.0-v15
    networks:
      - app-network

networks:
  app-network:
    driver: bridge