server:
  port: 8080

spring:
  application:
  name: y5-market

  jpa:
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: embedded
      data-locations: classpath:sql/data.sql

  h2:
    console:
      enabled: true
