server:
  port: 8080

spring:
  application:
  name: y6-market

r2dbc:
  url: r2dbc:h2:mem:///~/db/testdb;MODE=MYSQL
  username: test
  password: test

#  jpa:
#    defer-datasource-initialization: true
#
#  datasource:
#    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  sql:
    init:
      mode: embedded
      data-locations: classpath:sql/data.sql

#  h2:
#    console:
#      enabled: true

logging:
  level:
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG # заодно включим логирование SQL-запросов
    io.r2dbc: DEBUG # и добавим больше деталей (не включать в настоящем приложении)
